#!/usr/bin/env bash

OUTDIR="library"
SUPPORTED_VARIANTS=(
	"alpine"
	"debian"
	"debian-minimal"
	"minimal"
	# "rocky"
	"ubuntu"
	"ubuntu-minimal"
)

function releases() {
	gh api repos/webserver-llc/angie/releases --jq '.[].tag_name' \
		| cut -d- -f2
}

function releases_filter() {
	grep -i -E "1.10|1.11"
}

function stdout() {
	echo "$@"
}

function stderr() {
	echo "$@" >&2
}

GITHUB_RELEASES=$(releases | releases_filter)
GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER:-"socheatsok78"}
GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-"\${GITHUB_REPOSITORY_OWNER}/docker-angie"}

function dockerbakefile() {
	local version="$1"
	local manifest;
	echo "// This file is generated by \"$(basename "$0")\" script, do not edit it manually."
	echo ""
	echo "variable \"GITHUB_REPOSITORY_OWNER\" {"
	echo "  default = \"${GITHUB_REPOSITORY_OWNER}\""
	echo "}"
	echo ""
	echo "variable \"GITHUB_REPOSITORY\" {"
	echo "  default = \"${GITHUB_REPOSITORY}\""
	echo "}"
	echo ""
	echo "variable \"REPOSITORY\" {"
	echo "  default = replace(GITHUB_REPOSITORY, \"docker-\", \"\")"
	echo "}"
	echo ""
	for variant in "${SUPPORTED_VARIANTS[@]}"; do
		echo "target \"angie-${variant}-metadata\" {"
		manifest=$(cat hacks/manifest.json)
		if [[ "${variant}" != "debian-minimal" ]] && [[ "${variant}" != "ubuntu-minimal" ]]; then
			manifest=$(docker manifest inspect "docker.angie.software/angie:${version}${variant:+-$variant}" 2>/dev/null)
			if [[ $? -ne 0 ]]; then
				stderr "WRN: Failed to fetch manifest for version ${version}${variant:+-$variant}, skipping."
				echo "}"
				echo ""
				continue
			fi
		fi
		if [[ "${manifest}" == "" ]]; then
			stderr "WRN: No manifest found for version ${version}${variant:+-$variant}, skipping."
			echo "}"
			echo ""
			continue
		fi
		stderr "INF: Found manifest for version ${version}${variant:+-$variant}."
		echo "  args = {"
		echo "    \"ANGIE_VERSION\" = \"${version}\""
		echo "    \"ANGIE_VARIANT\" = \"${variant}\""
		echo "  }"
		echo "  platform = ["
		for platform in $(echo "${manifest}" | jq -r '.manifests[].platform | select(.os == "linux") | "\(.os)/\(.architecture)"'); do
			echo "    \"${platform}\","
		done
		echo "  ]"
		echo "  tags = ["
		short_version=$(echo "$version" | cut -d '.' -f 1-2)
		if [[ "${version}" == "$(echo "$GITHUB_RELEASES" | grep "$short_version" | head -n1)" ]]; then
			if [[ "${variant}" == "alpine" ]]; then
				echo "    \"docker.io/\${REPOSITORY}:${short_version}\","
				echo "    \"ghcr.io/\${REPOSITORY}:${short_version}\","
			fi
			echo "    \"docker.io/\${REPOSITORY}:${short_version}${variant:+-$variant}\","
			echo "    \"ghcr.io/\${REPOSITORY}:${short_version}${variant:+-$variant}\","
		fi
		if [[ "${variant}" == "alpine" ]]; then
			echo "    \"docker.io/\${REPOSITORY}:${version}\","
			echo "    \"ghcr.io/\${REPOSITORY}:${version}\","
		fi
		if [[ "${variant}" == "minimal" ]]; then
			if [[ "${version}" == "$(echo "$GITHUB_RELEASES" | sort -r --version-sort | head -n1)" ]]; then
				echo "    \"docker.io/\${REPOSITORY}:minimal\","
				echo "    \"ghcr.io/\${REPOSITORY}:minimal\","
			fi
		fi
		echo "    \"docker.io/\${REPOSITORY}:${version}${variant:+-$variant}\","
		echo "    \"ghcr.io/\${REPOSITORY}:${version}${variant:+-$variant}\""
		echo "  ]"
		echo "}"
		echo ""
	done
}

function main() {
	local overwrite=false
	while [ "$#" -gt 0 ]; do
		case "$1" in
			--outdir)
				OUTDIR="$2"
				shift 2
				;;
			--overwrite)
				overwrite=true
				echo "INF: Overwrite mode enabled, existing versions will be overwritten."
				shift 1
				;;
			*)
				echo "Usage: $0 [--overwrite] [--outdir <output directory>]"
				exit 1
				;;
		esac
	done
	echo "$GITHUB_RELEASES" | while read -r version; do
		if [ "${overwrite}" = true ]; then
			rm -rf "${OUTDIR:?}/${version}"
		fi
		if [ -d "${OUTDIR:?}/${version}" ]; then
			echo "WRN: Skipping version ${version} because it already exists."
			continue
		fi
		echo "INF: Generating files for release ${version}..."
		mkdir -p "${OUTDIR:?}/${version}"
		dockerbakefile "$version" > "${OUTDIR:?}/${version}/docker-bake.hcl"
	done
}

main "${@}"
