#!/usr/bin/env bash

set -e

outdir="library"
supported_variants=(
	"alpine"
	"debian"
	"minimal"
	# "rocky"
	"ubuntu"
)

function releases() {
	gh api repos/webserver-llc/angie/releases --jq '.[].tag_name' \
		| cut -d- -f2
}

function releases_filter() {
	grep -i -E "1.10|1.11"
}

GITHUB_RELEASES=$(releases | releases_filter)
GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER:-"socheatsok78"}
GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-"${GITHUB_REPOSITORY_OWNER}/docker-angie"}

function dockerbakefile() {
	local version="$1"
	echo "// This file is generated by \"$(basename "$0")\" script, do not edit it manually."
	echo ""
	echo "variable \"GITHUB_REPOSITORY_OWNER\" {"
	echo "  default = \"${GITHUB_REPOSITORY_OWNER}\""
	echo "}"
	echo ""
	echo "variable \"GITHUB_REPOSITORY\" {"
	echo "  default = \"${GITHUB_REPOSITORY}\""
	echo "}"
	echo ""
	for variant in "${supported_variants[@]}"; do
		echo "target \"angie-${variant}-metadata\" {"
		echo "  args = {"
		echo "    \"ANGIE_VERSION\" = \"${version}\""
		echo "    \"ANGIE_VARIANT\" = \"${variant}\""
		echo "  }"
		echo "  tags = ["
		short_version=$(echo "$version" | cut -d '.' -f 1-2)
		if [[ "${version}" == "$(echo "$GITHUB_RELEASES" | grep "$short_version" | head -n1)" ]]; then
			if [[ "${variant}" == "alpine" ]]; then
				echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${short_version}\","
				echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${short_version}\","
			fi
			echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${short_version}${variant:+-$variant}\","
			echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${short_version}${variant:+-$variant}\","
		fi
		if [[ "${variant}" == "alpine" ]]; then
			echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}\","
			echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}\","
		fi
		if [[ "${variant}" == "minimal" ]]; then
			if [[ "${version}" == "$(echo "$GITHUB_RELEASES" | sort -r --version-sort | head -n1)" ]]; then
				echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:minimal\","
				echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:minimal\","
			fi
		fi
		echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}${variant:+-$variant}\","
		echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}${variant:+-$variant}\""
		echo "  ]"
		echo "}"
		echo ""
	done
}

echo "$GITHUB_RELEASES" | while read -r version; do
	if [ -d "${outdir}/${version}" ]; then
		echo "WRN: Skipping version ${version} because it already exists."
		continue
	fi
	echo "INF: Generating docker-bake.hcl for version ${version}..."
	mkdir -p "${outdir}/${version}"
	dockerbakefile "$version" > "${outdir}/${version}/docker-bake.hcl"
done
